services:
  - type: web
    name: f1-api-gerard
    runtime: python
    buildCommand: pip install --upgrade pip && pip install fastf1 flask pandas
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0